config/routes.rb
Invite::Application.routes.draw do
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "profile" => "users#profile", :as => "profile"
  put "profile" => "users#update_profile", :as => "profile"
  delete 'session' => "sessions#destroy", :as => "log_out"
  resources :users  
  resources :sessions, :only => [:new, :create, :destroy] 
  root :to => 'home#index'
  
  namespace :admin do
     resources :users
     resources :invitations, :only => [:index, :show, :new, :create]
     root :to => "users#index"
  end
end

app/views/admin/invitations/_form.html.erb
<%= form_for [:admin, @invitation] do |f| %>
  <% @invitation.errors.full_messages.each do |msg| %>
      <div class="alert alert-error"><%= msg %></div>
  <% end %> 
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/invitations/index.html.erb
<h2>Invitations</h2>

<table class='table table-striped'>
  <tr>
    <th>Email</th>
    <th>Link</th>
    <th>Sended at</th>
    <th >Actions</th>
  </tr>
  <% unless @invitations.blank? %>
    <% for invitation in @invitations %>
      <tr>
        <td><%= invitation.email %></td>
        <td><%= invitation.link %></td>
        <td><%= invitation.updated_at %></td>
        <td><%= link_to "Show", [:admin, invitation] %></td>
      </tr>
    <% end %>
  <% end %>
<%= paginate @invitations %>
</table>

<p><%= link_to "New Invitation", new_admin_invitation_path,  :class=>'btn btn-success' %></p>

app/views/admin/invitations/new.html.erb
<h2>New Invitation</h2>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_invitations_path %></p>

app/views/admin/invitations/show.html.erb
<h2>Invitation</h2>

<p>
  <strong>Name:</strong>
  <%= @invitation.email %>
</p>

<p>
  <%= link_to "View All", admin_invitations_path %>
</p>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %> 
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @user] %> |
  <%= link_to "View All", admin_users_path %>
</p>

app/views/admin/users/index.html.erb
<h2>Users</h2>

<table class='table table-striped'>
  <tr>
    <th>Name</th>
    <th colspan=3>Actions</th>
  </tr>
  <% unless @users.nil?  %>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to "Show", [:admin, user] %></td>
        <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
        <td><%= link_to "Destroy", [:admin, user], :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
   <% end %>  
</table>
<%= paginate @users  %>

<p><%= link_to "New User", new_admin_user_path,  :class=>'btn btn-success'  %></p>

app/views/admin/users/new.html.erb
<h2>New User</h2>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_users_path %></p>

app/views/admin/users/show.html.erb
<h2>User</h2>

<p>
  <strong>Name:</strong>
  <%= @user.email %>
</p>

<p>
  <%= link_to "Edit", edit_admin_user_path(@user) %> |
  <%= link_to "Destroy", [:admin, @user], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_users_path %>
</p>

app/views/home/index.html.erb
<div>
  <h1>This is content of our closed system!  </h1> 
</div>  

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Admin" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
   
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner ">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <span class="brand">Admin</span>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Users", admin_users_path  %></li>
              <li><%= link_to "Invitations", admin_invitations_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <!--div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div >
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Invite1" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Invite</a>
          <div class="container-fluid nav-collapse">
            <% if user_signed_in?  %>

              <ul class="nav">
                <li><%= link_to "Link1", "/path1"  %></li>
              </ul>

              <%= render partial: 'shared/user_menu' %>

            <% end %>
          </div><!--/.nav-collapse -->


        </div>
      </div>
    </div>

    <div class="container-fluid">
      <% if current_user.try(:empty_phone?)  %>
      <%=  render partial: 'shared/reminder' %>
      <% end %>
      <div class="row-fluid">
        <!--div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div></.well -->
        </div></span-->
        <div class="span12">
         <% flash.each do |name, msg| %>  
         
  		  	<%= content_tag :div, :id => "flash#{name}", :class => "alert alert-#{name}" do %>  
  		  	<button type="button" class="close" data-dismiss="alert">&times;</button>
  		  	<%= msg %>
  		  	<% end  %>
         <% end %>  

         <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_reminder.html.erb
      <div class="row-fluid">
        <div class="span3 pull-right alert alert-info">
          <span>Please, fill out your phone in the 
            <%= link_to 'profile',profile_path %>
          </span>
        </div>
      </div>  

app/views/shared/_user_menu.html.erb
              <ul class="nav pull-right" >
                <li><span class=title>Logged in as: <%=current_user.email %></span> </li>
                <li><%= link_to "Profile",   profile_path  %></li>
                <li><%= link_to "Logout", log_out_path, :method => :delete  %></li>
              </ul>

app/views/users/edit.html.erb
<h2>Edit profile</h2>

<%= form_for @user, :url=>profile_path, :html => { :method => :put } do |f| %>

  <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-error"><%= msg %></div>
  <% end %> 

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>
  
  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password, :autocomplete => "off" %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>
  
  <div><%= f.label :name %><br />
  <%= f.text_field :name  %></div>

  <div><%= f.label :phone %><br />
  <%= f.text_field :phone  %></div>

  <div><%= f.label :addr,'Addres' %><br />
  <%= f.text_field :addr  %></div>


  <div><%= f.submit "Update" %></div>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>


<%= form_for @user do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-error"><%= msg %></div>
  <% end %> 

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :value=>@user.email, :readonly => true %></div>
  <%= f.hidden_field :link, :value=>params[:link] %>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>